### ISSUE TITLE
[Tracking] Materialisation

### ISSUE THREAD

**Issue by sandreae** [p2panda/p2panda#158]
# Materialisation Action Plan

> Materialise a collection of `Entries` and their `Operations` into resolved data instances. 

Below is a draft implementation of new core types needed for materialisation (excuse the psuedo-code), it's all work in progress, wanted to share these ideas and work through any feedback/suggestions here. Will try to split the implementation into manageable smaller PRs and keep track of it all here as well. 

## Milestones

- [x] basic graph (DAG) logic https://github.com/p2panda/p2panda/pull/129
- [x] ~`AsGraph` and `AsNode` traits~ now planning to use [incremental-topo](https://github.com/declanvk/incremental-topo) for graph building and sorting 
- [x] `Instance` type (derived from a Schema?) #161 
- [x] introduce `previous_operations` field for `Operation` struct https://github.com/p2panda/p2panda/pull/163
- [x] `OperationWithMeta` struct https://github.com/p2panda/p2panda/pull/163
- [x] `AsOperation` trait https://github.com/p2panda/p2panda/pull/163
- [ ] `Document` struct https://github.com/p2panda/p2panda/pull/169

## Folder structure

```
materialisation
├── document
├── instance
├── graph
└── ???
```

## Relevant specs

- `Document` https://laub.liebechaos.org/wYzMa0w8S12iYvQommrdrA?view
- `Operation` https://laub.liebechaos.org/7cGHWPCcR8eoZBkk-X9R4w?view
- `Instance` ?? 
- `KeyGroup` https://github.com/p2panda/handbook/pull/118
- graph API can be based on https://gitlab.com/tangle-js/tangle-graph/-/tree/master

## p2panda handbook

- https://p2panda.org/handbook/docs/
- https://github.com/p2panda/handbook/pull/116

## Related issues

- https://github.com/p2panda/p2panda/issues/135 
- https://github.com/p2panda/p2panda/issues/134 
- https://github.com/p2panda/p2panda/issues/127 
- https://github.com/p2panda/p2panda/issues/133 
- https://github.com/p2panda/p2panda/issues/132 
- https://github.com/p2panda/handbook/issues/123 
- https://github.com/p2panda/handbook/issues/123
- https://github.com/p2panda/handbook/issues/120 
- https://github.com/p2panda/handbook/issues/112 
- https://github.com/p2panda/handbook/issues/110
- https://github.com/p2panda/handbook/issues/79 
- https://github.com/p2panda/handbook/issues/75

## Materialisation Flow

General flow needed for materialising. Not all of this will be addressed right now, but good to know where things might need to happen.

- Query DB*
    - schema instance for this document
    - key_group instance for this document
    - all entries for this document by any author in key_group
- Filter*
    - any entries above highest `to` hash of KeyGroupLimit ranges for each author removed/ignored
- Initiate document
    - construct `OperationWithMeta` from `Entries` + `Operations`
    - construct document from `[OperationWithMeta]`, `Schema` & `KeyGroup`*
- Reduce
    - topologically sort operation graph
      - visit branches with lowest hash first
      - if `Operation` with >1 `previous_operations` found visit those dependencies first
    - at each node
        - validate node insertion (check it follows DAG law)
        - check if previous or next operations is >1
        - check KeyGroupLimits at each step of the graph and modify permission state accordingly*
        - validate operation
        - apply operations to instance
    - validate and return instance

_*out of scope for now_

### Document

`Document` encapsulates all logic necessary for materialising an array of `OperationWithMeta` into a single reduced `Instance`. It is constructed from an array of `OperationWithMeta`, a `Schema` and a `KeyGroup`. Its primary method is `reduce()` which returns a materialised `Instance`.
```rust

struct Document {
    id: Hash
    schema: Hash
    owners: KeyGroup
    operations: OperationWithMeta
}

impl Document {
    // Reduce the operation graph, return a Result containing `Some(Instance)`.
    // `None`is returned if the instance has been deleted.
    reduce() -> Result<Instance> {}
}
 
```

### `Operation`, `OperationWithMeta` types and `AsOperation` trait 

`Operations` are a core p2panda type which describe changes applied to data on the network. `OperationWithMeta` contains an `Operation` plus extra meta data derived from the operations containing `Entry` This meta data is needed during materialisation. Both structs implement the `AsOperation` trait. 

```rust
// Operation struct, this will replace Message and is used when publishing, storing and retrieving Operations
struct Operation {
    action: OperationAction,
    schema: Hash,
    version: OperationVersion,
    previous_operations: [Hash],
    fields: Option<OperationFields>
}

impl Operation {
    // Operation specific methods...    
}

// OperationWithMeta struct is needed in materialisation, it contains an `Operation` and some meta fields
struct OperationWithMeta {
    id: Hash,
    public_key: PublicKey,
    operation: Operation,
}

impl OperationWithMeta {
    // OperationWithMeta specific methods...    
}

// Trait methods which are implemented by both `Operation` and `OperationWithMeta`.
// The getters must be implemented for both structs, whereas all other methods can be 
// defined (using the getters) in the trait and then derived on the respective type.
trait AsOperation {
    get_action(&self) -> OperationAction {}
    get_schema(&self) -> Hash {}
    get_version(&self) -> OperationVersion {}
    get_document_id(&self) -> Hash {}
    get_previous_operations(&self) -> [Hash] {}
    get_fields(&self) -> Option<OperationFields>
    /// etc...
    /// all other operation specific methods use these trait getters
}

impl AsOperation for Operation {
    get_action(&self) -> OperationAction {
        self.action
    }
    get_schema(&self) -> Hash {
        self.schema
    }
    // etc...
}

impl AsOperation for OperationWithMeta {
    get_action(&self) -> OperationAction {
        self.operation.get_action()
    }
    get_schema(&self) -> Hash {
        self.operation.get_schema()
    }
    // etc...
}

```

### Instance

Represents the materialised view of a Document. It is constructed from a `Schema` and mutated throughout graph traversal into it final state. (nb: see p2panda-js for implementation ideas).

```rust
// Somehow this struct would be generated from a Schema (tbc)
struct Instance(HashMap<String, OperationValue>)

// Generic trait abstraction of ´Instance´ logic which any instance type can implement.
// ´Instances´ can be generated from their related ´Schema´
trait Instance {
    // Update this instance
    fn update(&mut self, fields: OperationFields) -> Result<> {}
    
    // Delete this instance
    fn delete(&mut self) -> Result<> {}
    
    // The schema of this instance
    fn schema(&self) -> Schema {}

    fn validate_operation(&self, fields: OperationFields) -> Result<> {
        // use self.schema() here.
    } 
}
```
==============================
### Bonus material, KeyGroup/ownership implementation ideas
```rust

trait Owned {
    // is this item owned by association with a PublicKey?
    fn has_public_key() -> bool {}
    
    // is this item owned by association with a KeyGroup?
    fn has_key_group() -> bool {}
    
    // Return the KeyGroup associated with the type which implements this trait
    fn key_group(&self) -> Option<KeyGroup> {}
    
    // Return public keys contained in the owner `KeyGroup` OR the single `PublicKey` association.
    fn authors(&self) -> [PublicKey] {}
    
    // Calculate and return the initial permissisons state derived from PublicKey OR KeyGroup
    fn permissions(&self) -> PermissionState {}
    
    // Check a public key against the owners of this item
    fn is_owner(&self, public_key: PublicKey) -> bool {}
    
    // Check if a public key is an owner which has limits
    fn has_limit(&self, public_key: PublicKey) -> bool {}
    
    // Mutate permission state based on KeyGroup limits
    fn mutate_permissions(&self, permissions_state: &mut PermissionState, operation_id: Hash) {}
}


// implement Owned trait (see below for definition)
impl Owned for Document {
    fn key_group(&self) -> KeyGroup {
        self.owners
    }
}

impl Owned for OperationWithMeta {
    fn key_group(&self) -> KeyGroup {
        self.owners
    }
}
```
